# Generated by Django 6.0.2 on 2026-03-08 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='numero_wpp',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='venda',
            name='senha',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='venda',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('pronto', 'Pronto')], default='pendente', max_length=10),
        ),
    ]
