# Generated by Django 6.0.2 on 2026-05-16 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0002_venda_numero_wpp_venda_senha_venda_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='tipo',
            field=models.CharField(choices=[('comida', 'Comida'), ('bebida', 'Bebida')], default='comida', max_length=10),
        ),
    ]
